"""LLM Service — DeepSeek integration for tone-refining explanations.

Uses the OpenAI-compatible API provided by DeepSeek.  Only used to rewrite
rule-generated natural-language explanations for tone; all outfit selection
and core styling logic remain rule-based and deterministic.
"""

from __future__ import annotations

from openai import APIConnectionError, APIError, AsyncOpenAI, RateLimitError

from backend.core.config import Settings, get_settings
from backend.core.exceptions import LLMError
from backend.core.logging import get_logger
from backend.core.tracing import get_tracer

logger = get_logger(__name__)

# ──────────────────────────────────────────────────────────────────────
#  Prompts
# ──────────────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = (
    "You are a professional fashion stylist AI. "
    "Given deterministic outfit reasoning text, rewrite only the tone to sound natural and polished. "
    "Never add, remove, or invent clothing items, colors, styles, or constraints. "
    "Keep each response under 100 words and do not use markdown formatting."
)

_OUTFIT_PROMPT = (
    "Detected base item: {detected_color} {detected_type} ({detected_style}).\n"
    "Deterministic rule-based explanation:\n"
    "{rule_text}\n\n"
    "Rewrite this explanation for tone only. Preserve all facts exactly."
)

_ITEM_PROMPT = (
    "Detected base item: {detected_color} {detected_type} ({detected_style}).\n"
    "Deterministic rule-based reason:\n"
    "{rule_text}\n\n"
    "Rewrite this sentence for tone only. Preserve all facts exactly."
)


class LLMService:
    """Async wrapper around the DeepSeek API for explanation tone refinement.

    Falls back gracefully if the API key is missing, the service is
    unavailable, or rate limits are hit.
    """

    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or get_settings()
        self._enabled = bool(self._settings.deepseek_api_key)

        if self._enabled:
            self._client = AsyncOpenAI(
                api_key=self._settings.deepseek_api_key,
                base_url=self._settings.deepseek_base_url,
            )
        else:
            self._client = None  # type: ignore[assignment]
            logger.warning("llm_disabled", reason="DEEPSEEK_API_KEY not set")

    @property
    def enabled(self) -> bool:
        return self._enabled

    async def _chat(self, user_prompt: str) -> str:
        """Send a chat completion request and return the text response."""
        if not self._enabled:
            raise LLMError("LLM service is disabled (no API key)")

        try:
            with get_tracer().generation(
                "deepseek.chat",
                model=self._settings.deepseek_model,
                input=user_prompt,
            ) as generation:
                response = await self._client.chat.completions.create(
                    model=self._settings.deepseek_model,
                    messages=[
                        {"role": "system", "content": _SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=self._settings.llm_temperature,
                    max_tokens=self._settings.llm_max_tokens,
                )
                content = (response.choices[0].message.content or "").strip()
                if generation is not None:
                    usage = getattr(response, "usage", None)
                    generation.update(
                        output=content,
                        usage_details=(
                            {"input": usage.prompt_tokens, "output": usage.completion_tokens} if usage else None
                        ),
                    )
                return content
        except (APIConnectionError, RateLimitError, APIError) as exc:
            logger.warning("llm_api_error", error=str(exc))
            raise LLMError(f"DeepSeek API error: {exc}") from exc

    async def generate_outfit_explanation(
        self,
        *,
        detected_type: str,
        detected_color: str,
        detected_style: str,
        rule_text: str,
    ) -> str:
        """Refine a deterministic outfit explanation for tone only.

        Args:
            detected_type: E.g. "shirt"
            detected_color: E.g. "navy"
            detected_style: E.g. "minimalist"
            rule_text: Deterministic explanation generated by rule engine.

        Returns:
            Tone-refined explanation string.
        """
        prompt = _OUTFIT_PROMPT.format(
            detected_type=detected_type,
            detected_color=detected_color,
            detected_style=detected_style,
            rule_text=rule_text,
        )
        return await self._chat(prompt)

    async def generate_item_reason(
        self,
        *,
        detected_type: str,
        detected_color: str,
        detected_style: str,
        rule_text: str,
    ) -> str:
        """Refine a deterministic one-sentence item reason for tone only."""
        prompt = _ITEM_PROMPT.format(
            detected_type=detected_type,
            detected_color=detected_color,
            detected_style=detected_style,
            rule_text=rule_text,
        )
        return await self._chat(prompt)
