"""initial_tables

Revision ID: 02b9134af48d
Revises:
Create Date: 2026-04-13 22:49:02.334753

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "02b9134af48d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
